[package]
name = "swap"
version = "0.1.0"
authors = ["daniel <zietdan@hu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
